name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan studio14.danaletordaniela.com >> ~/.ssh/known_hosts

      - name: Push to Dokku
        run: |
          git remote add dokku dokku@studio14.danaletordaniela.com:wordpress || true
          git push dokku HEAD:main
