name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOKKU_HOST: studio14.danaletordaniela.com
  DOKKU_APP: wordpress

jobs:
  build:
    name: Build (checkout)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.DOKKU_HOST }} >> ~/.ssh/known_hosts

      - name: Push to Dokku
        run: |
          git remote add dokku dokku@${{ env.DOKKU_HOST }}:${{ env.DOKKU_APP }} || true
          git push dokku HEAD:main

  rollback:
    name: Rollback on Deploy Failure
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start ssh-agent & add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}

      - name: Add Dokku server to known_hosts
        run: |
          ssh-keyscan -H ${{ env.DOKKU_HOST }} >> ~/.ssh/known_hosts

      - name: Determine rollback ref
        id: choose_ref
        run: |
          # Use previous deployed tag if available, otherwise fallback to HEAD~1
          if [ -n "${{ needs.deploy.outputs.deployed_tag }}" ]; then
            echo "Using previous tag ${{ needs.deploy.outputs.deployed_tag }}"
            echo "ref=${{ needs.deploy.outputs.deployed_tag }}" >> $GITHUB_OUTPUT
          else
            echo "No prior deployed tag—falling back to HEAD~1"
            echo "ref=HEAD~1" >> $GITHUB_OUTPUT
          fi

      - name: Rollback to determined ref
        run: |
          echo "Rolling back Dokku to ${{ steps.choose_ref.outputs.ref }}"
          git remote add dokku dokku@${{ env.DOKKU_HOST }}:${{ env.DOKKU_APP }} || true
          git push dokku "${{ steps.choose_ref.outputs.ref }}":main --force
